// src/config/formsConfig.js
// 🔥 SOLO CAMBIA LOS LINKS AQUÍ - NO TOQUES NADA MÁS

export const FORM_CONFIGS = [
  { id: 1, name: 'Antidoto – 300 9741660', url: 'https://forms.gle/7AdMT5JaHzjQBquK6' },
  { id: 2, name: 'Atiba – Cra 4 # 5-19', url: 'https://forms.gle/xTU3pNHe8hr7yirbA' },
  { id: 3, name: 'Bocados – Cra 15 # 9-44 Las Lajas', url: 'https://forms.gle/yVYxK7Wndvi7nex17' },
  { id: 4, name: 'Burger Hot – Calle 8 con Cra 14', url: 'https://forms.gle/BpbQ4SAJXjrhRK8UA' },
  { id: 5, name: 'Burger Hunter – 301 9557383', url: 'https://forms.gle/mGizB7ip2nycbQot9' },
  { id: 6, name: 'Caoba – Calle 11 # 5-23 Santa Rita', url: 'https://forms.gle/mGizB7ip2nycbQot9' },
  { id: 7, name: 'Conejo\'s Pizza – Calle 2 Este # 7-41', url: 'https://forms.gle/Sg6kzHBCuCjz2Qi29' },
  { id: 8, name: 'DaniBurgers – Calle 2 Este # 7-82 La Arboleda', url: 'https://forms.gle/BKDpqtpYyqgsHB7G7' },
  { id: 9, name: 'De Gula – Calle 8 # 6-23', url: 'https://forms.gle/dkmwkqGySahXd23D6' },
  { id: 10, name: 'Don Barriga – Cra 5 # 13-51', url: 'https://forms.gle/1Jy7JMUpHPBw9P488' },
  { id: 11, name: 'Dorilocos – Cra 4 # 8-27', url: 'https://forms.gle/1Yynzrby3kNb7u6y6' },
  { id: 12, name: 'El Andino – Cra 5 # 11-19 Santa Rita', url: 'https://forms.gle/r5uB6nnUTSLF81W19' },
  { id: 13, name: 'El Faro – Calle 8 # 4-84', url: 'https://forms.gle/cPJV8UTWLEBXp7dE9' },
  { id: 14, name: 'Faca Food – Cra 5 # 15-145', url: 'https://forms.gle/nNvMqhGi1WMD1qhe9' },
  { id: 15, name: 'Fries – Cra 5 # 10-41 Santa Rita', url: 'https://forms.gle/bHhoHg9DW3YKvB3DA' },
  { id: 16, name: 'Gustazo – Diag 148 # 52-198 Llano Popular', url: 'https://forms.gle/hDEcxuZ3oPy1LCek7' },
  { id: 17, name: 'J/S Pizzería – Calle 2A # 8-03', url: 'https://forms.gle/s8oVV93rysCa2pvN6' },
  { id: 18, name: 'Jugoson – Cra 15 # 5A-06 Dos Caminos', url: 'https://forms.gle/Rd5C5u7BquURFxzD6' },
  { id: 19, name: 'La Boca – Cra 5 # 10-41', url: 'https://forms.gle/zNxFHrrLuHNYwYps7' },
  { id: 20, name: 'La Roca Burger – Cra 7 # 9-91 Santa Rita', url: 'https://forms.gle/QTDH6R1kcRXZxxgh7' },
  { id: 21, name: 'Mr Pizza – Cra 5 # 13-93 Omnicentro', url: 'https://forms.gle/my5SFjmnegmaP9s99' },
  { id: 22, name: 'Mr Toppings – Cra 7 # 5-40', url: 'https://forms.gle/4JoKmbKU8aPJSHWCA' },
  { id: 23, name: 'Oh My Dog – Calle 8 # 3A-65', url: 'https://forms.gle/DkU9T71eV6usMY5NA' },
  { id: 24, name: 'Oregon BBQ – 320 2409660', url: 'https://forms.gle/Jr3mdnbvgt9r4QMr9' },
  { id: 25, name: 'Papo Burger – Cra 5 # 4-12', url: 'https://forms.gle/7SqNHAXyEH97mW148' },
  { id: 26, name: 'Patatas House – Cra 4 # 8-23', url: 'https://forms.gle/2d334Tn81jW7BPhdA' },
  { id: 27, name: 'Pecado Capital – Calle 11 # 5-07', url: 'https://forms.gle/rZcMB1Le7xY2fj7H9' },
  { id: 28, name: 'Pedacito de Cielo – Cra 3 # 8-56', url: 'https://forms.gle/DGnBhktt9yATn2yN9' },
  { id: 29, name: 'Pilón Burguer – Calle 2A Este # 7-48', url: 'https://forms.gle/vdARuZyTWNPZUJpQA' },
  { id: 30, name: 'Punto Burguer – Calle 8 # 6-19', url: 'https://forms.gle/o2dakUwnP7RfEUnA8' },
  { id: 31, name: 'Sabor Urbano – Cra 15 # 9-13', url: 'https://forms.gle/1dpKGnV2FmmJCD4J9' },
  { id: 32, name: 'Texas BBQ – Cra 4 # 7-167', url: 'https://forms.gle/zWyXGqEdNjvmiVeW8' },
  { id: 33, name: 'Viñas Food – Calle 11 # 8-03', url: 'https://forms.gle/5EmYjg7D2DvUfqMX8' },
  { id: 34, name: 'Yadah Food – Calle 12 # 6-42', url: 'https://forms.gle/SGvSu8onhroS9Dm9A' },
  { id: 35, name: 'Y&Y Burgers – Calle 8 # 7A-10', url: 'https://forms.gle/1m52oJKa5TmMUdgo6' },
  { id: 36, name: 'Yokai – Calle 15 # 4-59 Los Molinos Serai', url: 'https://forms.gle/QeSh31tFu7TAz5eZ9' },
  { id: 37, name: 'Formulario 37', url: 'https://forms.gle/QeSh31tFu7TAz5eZ9' },
  { id: 38, name: 'Formulario 38', url: 'https://forms.gle/KSpCWexTUXkYMfnTA' },
];

// ⚠️ NO CAMBIES NADA ABAJO DE ESTA LÍNEA
export default FORM_CONFIGS;